### ISSUE TITLE
It's necessary to resolve the PR opened by dependabot

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/mc-data-manager#16]
Dependabot이 생성한 PR에 대해서도 살펴보시고 처리해주시면 될 것 같습니다.
* 선 머지, 후 대응 하시거나,
* 파악 후, 머지하시는 방식 모두 가능합니다.

#1 
#2

메인테이너께서 판단하시기에 적절한 시점에 진행해 주시기 바랍니다.

**Comment by seokho-son** [comment]
FYI @heedaeshin @yunkon-kim 

- resolved by https://github.com/cloud-barista/mc-data-manager/pull/30
  - https://github.com/cloud-barista/mc-data-manager/pull/1
  - https://github.com/cloud-barista/mc-data-manager/pull/2

**Comment by heedaeshin** [comment]
@yunkon-kim @seokho-son 
확인하였습니다. 
디펜던시 점검 과정 및 머지 여부 리뷰에 남겨 진행하도록 하겠습니다.

**Comment by yunkon-kim** [comment]
Resolved :-)
