### ISSUE TITLE
Golang version for M-CMP v0.3.0

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/mc-data-manager#17]
활용하는 Golang 버전을 1.23 으로 지정하고자 합니다.
각 서브시스템에서는 Golang 버전을 1.23으로 올려서 프리릴리스 때 공유해주시길 요청 드립니다.

- 참고: https://github.com/cloud-barista/cb-tumblebug/issues/1756

**Comment by heedaeshin** [comment]
https://github.com/cloud-barista/mc-data-manager/pull/30
- 위 커밋에서 해당 이슈 완료 하였습니다.
