### ISSUE TITLE
About credential setup mechanism

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/mc-data-manager#40]
It's necessary to change the credential setup mechanism.

(As-Is) API 호출 시, credential을 인자로 입력 받고 있음
(To-bd) mc-data-manager 구동 초기에 설정하는 메커니즘으로 수정

상호 이해를 위해 개인적인 의견을 공유드립니다. 협소한 의견이오니 간단히 참고만 하시면 될 것 같습니다. 
: mc-data-manager에서 credential 등록 기능/방법 제공 하면, 향후 유연한 활용이 가능할 것으로 생각됩니다. 예를 들어,
  - mc-data-manager 구동 후, 사용자가 credential 등록 가능
  - mc-data-manager 구동 시, 외부 시스템으로 부터 credential 발급 받아서 등록 가능

Note - MC-IAM-MANAGER 활용/연동과 관련해서는 추후 협의사항 공유 예정

**Comment by heedaeshin** [comment]
- 사용자 등록기능
  - WEB UI, CLI, API 
  - 해당 인터페이스를 이야기 하시는 건지 확인 부탁드립니다.
- 외부시스템
  - 외부시스템에 대한 예시 부탁드립니다. 
     - m-cmp 내부, 외부 여부
     - 내부라면 어떤 서브 시스템에서 발급 요청하는지?

**Comment by yunkon-kim** [comment]
@heedaeshin 

항목 별로 말씀 드리겠습니다. 

> * 사용자 등록기능
>   
>   * WEB UI, CLI, API
>   * 해당 인터페이스를 이야기 하시는 건지 확인 부탁드립니다.

우선 credential을 특정 디렉토리에 저장하고, mc-data-manager가 구동 될 때 읽어서 활용하는 방향으로 진행해 주시면 될 것 같습니다. Terraform을 생각해보시면 조금 도움이 되실 것 같습니다. :-) 

설명드린 내용은 mc-data-manager 구동 전에 수행하는 사항인데요. 
등록이라는 관점으로 조금 바꿔서 바라보자면 자연스럽게 API, CLI가 필요하게 될 것 입니다.
Admin이 등록 기능을 통해 credential을 입력하면, 특정 디렉토리/저장소나 저장소에 등록이되고요.
처음 설명드린 mc-data-manager가 읽어서 활용하는 과정으로 이어집니다. 

또한, mc-data-manager가 구동 후, 타 서브시스템의 API호출로 credential을 획득한 후,
이를 저장 및 활용하는 과정 또한 비슷한 맥락이라고 볼 수 있겠습니다. 

설명드린 내용 살펴보시고 궁금한 사항이 있으시면 댓글로 남겨주세요.

> * 외부시스템
>   
>   * 외부시스템에 대한 예시 부탁드립니다.
>     
>     * m-cmp 내부, 외부 여부
>     * 내부라면 어떤 서브 시스템에서 발급 요청하는지?

추후 결정 될 사항이긴 하나, 내부적으로는 MC-IAM-MANAGER가 될 수 있고요. 외부적으로는 CSP, Vault등 이 될 수 있겠습니다.

**Comment by yunkon-kim** [comment]
Ref) Data Manager 사용 가이드 > 프로필 설정 가이드 > [프로필 설정 가이드](https://github.com/cloud-barista/mc-data-manager/blob/main/docs/Datamanager-Demo-Guide.md#%EC%82%AC%EC%A0%84-%EC%A4%80%EB%B9%84-%EC%82%AC%ED%95%AD)
